### ISSUE TITLE
您好！我在Pycharm打开这个项目代码，有一个依赖叫pinyin的没法在阿里云下载？

### ISSUE THREAD

**Issue by asdaca0** [cjh4312/stock-quotes#1]
您好！ 感谢您的分享。

问题如题：我在Pycharm打开这个项目代码，有一个依赖叫pinyin的没法在阿里云下载？

Looking in indexes: http://mirrors.aliyun.com/pypi/simple/

WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
ERROR: Could not find a version that satisfies the requirement pinyin (from versions: none)
ERROR: No matching distribution found for pinyin

python 3.9.7

conda activate D:\anaconda
D:\anaconda\python.exe D:/Program Files/JetBrains/PyCharm 2022.3.2/plugins/python/helpers/packaging_tool.py install pinyin --index-url http://mirrors.aliyun.com/pypi/simple/

**Comment by cjh4312** [comment]
换个源试试，https://pypi.douban.com/simple

**Comment by wjquant** [comment]
这个可以
https://pypi.org/project/pinyin/
pip install pinyin
